In [1]:
import torch
import sys
sys.version

'3.7.15 (default, Nov  5 2022, 17:23:33) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]'

In [2]:
import torch
torch.version.__version__

'1.4.0'

In [2]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
b = torch.ones(3,3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [9]:
# 指定计算设备
a = a.to('cuda')
b = b.to('cuda')
a + b

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

In [10]:
help(a.to)

Help on built-in function to:

to(...) method of torch.Tensor instance
    to(*args, **kwargs) -> Tensor
    
    Performs Tensor dtype and/or device conversion. A :class:`torch.dtype` and :class:`torch.device` are
    inferred from the arguments of ``self.to(*args, **kwargs)``.
    
    .. note::
    
        If the ``self`` Tensor already
        has the correct :class:`torch.dtype` and :class:`torch.device`, then ``self`` is returned.
        Otherwise, the returned tensor is a copy of ``self`` with the desired
        :class:`torch.dtype` and :class:`torch.device`.
    
    Here are the ways to call ``to``:
    
    .. function:: to(dtype, non_blocking=False, copy=False) -> Tensor
    
        Returns a Tensor with the specified :attr:`dtype`
    
    .. function:: to(device=None, dtype=None, non_blocking=False, copy=False) -> Tensor
    
        Returns a Tensor with the specified :attr:`device` and (optional)
        :attr:`dtype`. If :attr:`dtype` is ``None`` it is inferred to b