In [67]:
import torch

In [27]:
a=torch.tensor([[[1,2],[3,4]],
              [[5,6],[7,8]]], dtype=torch.float32)
print('a', a)
print('-1', a.mean(-1))
print('-2', a.mean(-2))

a tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
-1 tensor([[1.5000, 3.5000],
        [5.5000, 7.5000]])
-2 tensor([[2., 3.],
        [6., 7.]])


In [26]:
a=torch.tensor([[1,2],[3,4]], dtype=torch.float32)
print(a)
print(a.mean(-2))

tensor([[1., 2.],
        [3., 4.]])
tensor([2., 3.])


In [31]:
a=torch.ones(3,3)
print(a)
a=a.unsqueeze(-1)
print(a, a.shape)
a=a.unsqueeze(-1)
print(a, a.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.]]]) torch.Size([3, 3, 1])
tensor([[[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]],


        [[[1.]],

         [[1.]],

         [[1.]]]]) torch.Size([3, 3, 1, 1])


In [35]:
a=torch.tensor([[[1,2],[3,4]],
              [[5,6],[7,8]]], dtype=torch.float32)
print(a)
a=a * (torch.ones(2,2,2) * 2)
print(a)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
tensor([[[ 2.,  4.],
         [ 6.,  8.]],

        [[10., 12.],
         [14., 16.]]])


In [36]:
help(torch.einsum)

Help on function einsum in module torch.functional:

einsum(equation, *operands)
    einsum(equation, *operands) -> Tensor
    
    This function provides a way of computing multilinear expressions (i.e. sums of products) using the
    Einstein summation convention.
    
    Args:
        equation (string): The equation is given in terms of lower case letters (indices) to be associated
               with each dimension of the operands and result. The left hand side lists the operands
               dimensions, separated by commas. There should be one index letter per tensor dimension.
               The right hand side follows after `->` and gives the indices for the output.
               If the `->` and right hand side are omitted, it implicitly defined as the alphabetically
               sorted list of all indices appearing exactly once in the left hand side.
               The indices not apprearing in the output are summed over after multiplying the operands
               entri

In [68]:
# 两幅画，每幅画有两个点，每个点由两个坐标值表示
a=torch.tensor([[[1,2],[3,4]],
              [[5,6],[7,8]]], dtype=torch.float32)
print(a, a.shape)
a_names=a.refine_names('p', 'x', 'y')
print(a_names.shape, a_names.names)
print('-' * 40)
print(a_names)
print('sum(x):', a_names.sum('x'))
print('sum(-2):', a_names.sum(-2))
print('-' * 40)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]]) torch.Size([2, 2, 2])
torch.Size([2, 2, 2]) ('p', 'x', 'y')
----------------------------------------
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]], names=('p', 'x', 'y'))
sum(x): tensor([[ 4.,  6.],
        [12., 14.]], names=('p', 'y'))
sum(-2): tensor([[ 4.,  6.],
        [12., 14.]], names=('p', 'y'))
----------------------------------------


In [72]:
a = torch.ones(3, 2)
print('a', a)
# 生成一个新的tensor
a1=a.sin()
print('a1', a1)
print(id(a),id(a1))

a tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
a1 tensor([[0.8415, 0.8415],
        [0.8415, 0.8415],
        [0.8415, 0.8415]])
140470871739840 140470871815344


In [73]:
a = torch.ones(3, 2)
print('a', a)
# in place
a1=a.sin_()
print('a1', a1)
print(id(a),id(a1))

a tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
a1 tensor([[0.8415, 0.8415],
        [0.8415, 0.8415],
        [0.8415, 0.8415]])
140470872264864 140470872264864


In [76]:
a = torch.ones(3, 2)
a = a.storage()
print(a)
a[5] = 100
print(a)

 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.FloatStorage of size 6]
 1.0
 1.0
 1.0
 1.0
 1.0
 100.0
[torch.FloatStorage of size 6]
