In [1]:
import torch


In [4]:
a=torch.Tensor([1,2,3])
print(a.mean())
a=torch.Tensor([[1,2,3],[4,5,6]])
print(a.mean())
print(a[0].mean())

tensor(2.)
tensor(3.5000)
tensor(2.)


In [17]:
import numpy as np
np.reshape
a=np.arange(27)
a=a.reshape(3,3,3)
print(a)
print('-' * 40)
a = torch.from_numpy(a)
a = a.permute(2,0,1)
print(a)
print(a.shape)
print(a[1])
print(a[:,1])
print(a[:,1,1])
print(torch.sum(a[:,1,1]))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
----------------------------------------
tensor([[[ 0,  3,  6],
         [ 9, 12, 15],
         [18, 21, 24]],

        [[ 1,  4,  7],
         [10, 13, 16],
         [19, 22, 25]],

        [[ 2,  5,  8],
         [11, 14, 17],
         [20, 23, 26]]])
torch.Size([3, 3, 3])
tensor([[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]])
tensor([[ 9, 12, 15],
        [10, 13, 16],
        [11, 14, 17]])
tensor([12, 13, 14])
tensor(39)


In [19]:
import torch
help(torch.var)

Help on built-in function var:

var(...)
    .. function:: var(input, unbiased=True) -> Tensor
    
    Returns the variance of all elements in the :attr:`input` tensor.
    
    If :attr:`unbiased` is ``False``, then the variance will be calculated via the
    biased estimator. Otherwise, Bessel's correction will be used.
    
    Args:
        input (Tensor): the input tensor.
        unbiased (bool): whether to use the unbiased estimation or not
    
    Example::
    
        >>> a = torch.randn(1, 3)
        >>> a
        tensor([[-0.3425, -1.2636, -0.4864]])
        >>> torch.var(a)
        tensor(0.2455)
    
    
    .. function:: var(input, dim, keepdim=False, unbiased=True, out=None) -> Tensor
    
    Returns the variance of each row of the :attr:`input` tensor in the given
    dimension :attr:`dim`.
    
    
    If :attr:`keepdim` is ``True``, the output tensor is of the same size
    as :attr:`input` except in the dimension(s) :attr:`dim` where it is of size 1.
    Otherw